language: node_js

sudo: false

addons:
  chrome: stable

cache:
  directories:
    - node_modules

node_js:
  - "6"
  - "7"

before_install:
  google-chrome-stable --headless

script:
  - npm run test
